# Configure the interval in seconds (600 = 10 minutes)
clearInterval: 600

# Configure the time-format output
timeFormat:
  Years: 'Jahre'
  Year: 'Jahr'
  Months: 'Monate'
  Month: 'Monat'
  Weeks: 'Wochen'
  Week: 'Woche'
  Days: 'Tage'
  Day: 'Tag'
  Hours: 'Stunden'
  Hour: 'Stunde'
  Minutes: 'Minuten'
  Minute: 'Minute'
  Seconds: 'Sekunden'
  Second: 'Sekunde'