name: ClearLagg
version: '1.0'
main: net.dungeonhd.clearLagg.ClearLagg
api-version: '26.1.2'
authors: [ DungeonHD ]
description: Alle fallengelassenen Gegenstände werden alle 5 Minuten entfernt.
website: https://www.dungeonhd.net
commands:
  clearlagg:
    description: Haupt-Befehl für das Plugin

permissions:
  clearlagg.*:
    description: Gibt dir alle Berechtigungen für das Plugin
    children:
      clearlagg.command.*: true
  clearlagg.command.*:
    description: Gibt dir alle Berechtigungen für Befehle
    children:
      clearlagg.command.clearlagg: true
      clearlagg.command.reload: true
